# Site settings
title: Marcus Osterberg Blog
email: marcusterberg@gmail.com
description: Self-learned web developer who's on the journey of becoming better at his craft
baseurl: "" # the subpath of your site, e.g. /blog/
url: ""
disqus_account: marcusosterbergblog

# Social Usernames
twitter_username: osterbergmarcus
github_username: osterbergmarcus
medium_username: osterberg
codepen_username: osterbergmarcus

# Build settings
markdown: kramdown

excerpt_separator: ""   # Workaround for http://blog.slaks.net/2013-08-09/jekyll-tag-was-never-closed
