# Site settings
title: Marcus Osterberg CV
description: Marcus Osterberg CV
favicon:
baseurl:
url:
rss_url:

# Build settings
markdown: kramdown

# Author settings
author:
  name: Marcus Österberg
  title: Aspiring full-stack JavaScript developer
  address: Munich, Germany
  email: marcusterberg@gmail.com
  link: omarcusosterberg.com
  github: osterbergmarcus
  twitter: osterbergmarcus
  gavatar:
  workHistory:
    - work1:
      company: Gonutri
      location: Munich, Germany
      title: Co-founder, CTO
      started: 2015
      duration: (2015 - Present)
      description: Gonutri is an innovative platform that connects clients with their nutritionists. My biggest challenge for this project has been to  develop a web app that provides real time communication for our users.
      [linkid]: http://www.example.com/ "Optional Title"
    - work2:
      company: Portfolio
      location:
      title:
      started: 2015
      duration: (2015 - Present)
      description: Chat app built with JavaScript, Bootstrap and Firebase
    - education1:
      organization: John Bauer High School, Sweden
      degree: High School Degree equivalent to A-Level
      major:
      started: 2004
      duration: (2004 - 2007)
      description: School included an extensive IT program focusing on programming
  languages:
    - language1:
      name: Swedish
      proficiency: Native
    - language2:
      name: Norweigan
      proficiency: Professional
    - language3:
      name: Danish
      proficiency: Professional
    - language3:
      name: English
      proficiency: Professional
    - language3:
      name: German
      proficiency: Basic
  programmingSkills:
    - skill1:
      name: JavaScript, HTML, CSS, PHP
    - skill2:
      name: jQuery, vuejs, Polymer-project, Bootstrap, WordPress
